#!/bin/sh /etc/rc.common
# Basic init script
#
# Copyright (C) 2018 LPN Plant
#

START=95
USE_PROCD=1
PROG=/usr/sbin/swupdate_progress
PIDFILE=/var/run/swupdate_progress.pid

start_service() {
  procd_open_instance swupdate_progress
  procd_set_param command ${PROG} -w -r

  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

  procd_set_param pidfile ${PIDFILE} # write a pid file on instance start and remote it on stop
  procd_close_instance
}
